// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApi2t2gzA_sV35Wc7AD6e0mM_O4JzR6b0',
    appId: '1:1088024434191:web:e2728faed5d5917e89357a',
    messagingSenderId: '1088024434191',
    projectId: 'capstone-project-prod',
    authDomain: 'capstone-project-prod.firebaseapp.com',
    storageBucket: 'capstone-project-prod.firebasestorage.app',
    measurementId: 'G-XS51CTG0DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvDeB3nXcdrip6V8GauM3cW1_atFj06YA',
    appId: '1:1088024434191:android:e28c9a501648a33189357a',
    messagingSenderId: '1088024434191',
    projectId: 'capstone-project-prod',
    storageBucket: 'capstone-project-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Xe7kWRJiiqDE2B26JOrfFrT7SYfifTQ',
    appId: '1:1088024434191:ios:e6eee60b789f498d89357a',
    messagingSenderId: '1088024434191',
    projectId: 'capstone-project-prod',
    storageBucket: 'capstone-project-prod.firebasestorage.app',
    iosBundleId: 'com.example.rencanaku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6Xe7kWRJiiqDE2B26JOrfFrT7SYfifTQ',
    appId: '1:1088024434191:ios:446a6bc10e31149f89357a',
    messagingSenderId: '1088024434191',
    projectId: 'capstone-project-prod',
    storageBucket: 'capstone-project-prod.firebasestorage.app',
    iosBundleId: 'com.example.b25Pg011CapstoneProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApi2t2gzA_sV35Wc7AD6e0mM_O4JzR6b0',
    appId: '1:1088024434191:web:07f9a3dd9a7fa0ea89357a',
    messagingSenderId: '1088024434191',
    projectId: 'capstone-project-prod',
    authDomain: 'capstone-project-prod.firebaseapp.com',
    storageBucket: 'capstone-project-prod.firebasestorage.app',
    measurementId: 'G-8CRCGHQF3T',
  );
}
