// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApOLtNO91nAB7yCzAugk47tGKpDcIJ4zk',
    appId: '1:439975735447:web:90506fa8895040817b39d2',
    messagingSenderId: '439975735447',
    projectId: 'capstone-project-c0f48',
    authDomain: 'capstone-project-c0f48.firebaseapp.com',
    storageBucket: 'capstone-project-c0f48.firebasestorage.app',
    measurementId: 'G-W7J90GGN0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0jhqQjPi8COidPXiMI5lpDl5B9TW7qxg',
    appId: '1:439975735447:android:23d8d6df6395c1f67b39d2',
    messagingSenderId: '439975735447',
    projectId: 'capstone-project-c0f48',
    storageBucket: 'capstone-project-c0f48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXhWSWfAYBzCb4nQvf923V85Yr4qVhdCU',
    appId: '1:439975735447:ios:8474040f690131337b39d2',
    messagingSenderId: '439975735447',
    projectId: 'capstone-project-c0f48',
    storageBucket: 'capstone-project-c0f48.firebasestorage.app',
    iosBundleId: 'com.example.b25Pg011CapstoneProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXhWSWfAYBzCb4nQvf923V85Yr4qVhdCU',
    appId: '1:439975735447:ios:8474040f690131337b39d2',
    messagingSenderId: '439975735447',
    projectId: 'capstone-project-c0f48',
    storageBucket: 'capstone-project-c0f48.firebasestorage.app',
    iosBundleId: 'com.example.b25Pg011CapstoneProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApOLtNO91nAB7yCzAugk47tGKpDcIJ4zk',
    appId: '1:439975735447:web:f2501ccb310d36d97b39d2',
    messagingSenderId: '439975735447',
    projectId: 'capstone-project-c0f48',
    authDomain: 'capstone-project-c0f48.firebaseapp.com',
    storageBucket: 'capstone-project-c0f48.firebasestorage.app',
    measurementId: 'G-63Q9VF1BST',
  );
}
